// <auto-generated />
namespace work_tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_update_date_work_item_activity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_update_date_work_item_activity));
        
        string IMigrationMetadata.Id
        {
            get { return "202512021428294_added_update_date_work_item_activity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
