// <auto-generated />
namespace work_tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddSprint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSprint));
        
        string IMigrationMetadata.Id
        {
            get { return "202511120616180_AddSprint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
