// <auto-generated />
namespace work_tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class test_outlook_integration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_outlook_integration));
        
        string IMigrationMetadata.Id
        {
            get { return "202511200628598_test_outlook_integration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
