// <auto-generated />
namespace work_tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updated_timeentry_added_meeting_join : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_timeentry_added_meeting_join));
        
        string IMigrationMetadata.Id
        {
            get { return "202512011128235_updated_timeentry_added_meeting_join"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
