// <auto-generated />
namespace work_tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Infrastructure.Annotations;
    using System.Data.Entity.Migrations.Model;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0.0")]
    internal sealed partial class AddTimeEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTimeEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "202511201330000_AddTimeEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
        
        string IMigrationMetadata.Resources
        {
            get { return null; }
        }
    }
}