// <auto-generated />
namespace work_tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class coklu_sprint_takibi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(coklu_sprint_takibi));
        
        string IMigrationMetadata.Id
        {
            get { return "202511180955475_coklu_sprint_takibi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
